apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-images
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
