apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    app: http-go-app
  name: http-go-app
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
